### ISSUE TITLE
[BUG] preamble not possible in protocol anymore?

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/reproschema-py#47]
tried running main on my "cobidas" schemas

Tested the following on main.

This is valid.

```json
{
    "@context": "https://raw.githubusercontent.com/ReproNim/reproschema/1.0.0-rc4/contexts/generic",
    "@type": "reproschema:Protocol"
}
```

This is not valid (but was before).

```json
{
    "@context": "https://raw.githubusercontent.com/ReproNim/reproschema/1.0.0-rc4/contexts/generic",
    "@type": "reproschema:Protocol",
    "preamble": {
        "en": "foo"
    }
}
```

As far as I can tell preambles were part of the allowed properties in the previous version of the schema.

![image](https://github.com/ReproNim/reproschema-py/assets/6961185/780f53af-c29c-4dcf-bc6b-b10648f7b5d3)

**Comment by djarecka** [comment]
Ok, I will add `preamble` to `Protocol`. Thank you for pointing this
